### ISSUE TITLE
Build Error - Callback.h

### ISSUE THREAD

**Issue by kent-williams** [GrumpyOldPizza/ArduinoCore-stm32l0#133]
Hello @GrumpyOldPizza,

Many thanks for sharing this core and set of libraries!
I made a comment on a closed issue [here](https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0/issues/114#issuecomment-627378174), but thought it best to create a new issue as well.

When building with third party libraries that include "Wire.h", the following error still occurs:
```
Callback.h:70:44: error: 'NULL' was not declared in this scope operator bool() { return (_callback != NULL); }
```

Since each library is compiled separately, there is no declaration of NULL still when "Callback.h" gets included by Wire.h

Thanks!
-Kent

**Comment by GrumpyOldPizza** [comment]
After a bunch of retires this should finally be addressed.
